inherit_from: .rubocop_todo.yml

AllCops:
    NewCops: enable

Style/IfUnlessModifier:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

ClassAndModuleChildren:
    Enabled: false

Documentation:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/BlockComments:
    Enabled: false

Style/StringLiterals:
    Enabled: false
